name: 'Windows Code Signing'
description: 'Sign files with a PFX certificate.'
author: 'Sean Proctor'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the files to sign.'
    required: true
  recursive:
    description: 'Recursively search for supported files.'
    required: false
  password:
    description: 'The password'
    required: true
  timestampUrl:
    description: 'URL of the timestamp server'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
